### ISSUE TITLE
No Scroll Bar for Test Utility

### ISSUE THREAD

**Issue by GPREAPER** [TNotifier/Issues#10]
The Test button for the window that pops up for the test utility goes beyond the height of the window and there doesn't seem to be a scroll bar present

**Comment by Oyed** [comment]
Which Browser are you using? I had to make it a general height for Chrome, it sucks but there's no way I can dynamically set the height to it's right 100% of the time, can you resize the window?

**Comment by GPREAPER** [comment]
Atm I am using Chrome however the screen im using is only capable of 720p. It's a plasma tv that wasn't built to display computer screens but im still going through hdmi. I can increase it's resolution but it'll be beyond it's display range

**Comment by Oyed** [comment]
I will add a scrollbar to counter this - expect that tomorrow (It's midnight here, I'm going offline shortly). Will update this issue on the matter later tomorrow. Thanks!

**Comment by GPREAPER** [comment]
Alrighty then. Btw I use to beta test for Activision/Blizzard so I'm use to the process and I will try to nit pick everything for you. I'd like to see this work as best as possible.

**Comment by Oyed** [comment]
Thanks for your input! I've allowed a scrollbar in the Testing Utility now.
