### ISSUE TITLE
CLR Plugin Setup Image Covers Text

### ISSUE THREAD

**Issue by WLWarfare** [TNotifier/Issues#11]
Small issue but when you go to the guides page the text for "CLR Plugin Setup" is hard to read with the icon behind it.

**Comment by Oyed** [comment]
Due to me making the imagery on a fairly large monitor, so the text didn't reach that far for me. I'll reduce the image size.

**Comment by Oyed** [comment]
Closing for now - no real way to fix this other than to make the image tiny or move every image off-center (Needs to be uniform position).
