### ISSUE TITLE
Double "Create A...." Buttons

### ISSUE THREAD

**Issue by WLWarfare** [TNotifier/Issues#12]
I'm pretty sure it's not an issue but it seems out of place to have 2 buttons that say create a tracker, create a goal, etc. I know the middle one isn't displayed once you create one but having 2 just seems out of place. Maybe remove the top right one when they haven't created anything and then add it back if they have one. 

http://puu.sh/k3Lnp/62033735c9.png

**Comment by Oyed** [comment]
The middle one is a call to action button for convenience; could probably remove this, not entirely sure, I'll get back to you.

**Comment by Oyed** [comment]
Fixed - removed the call-to-action buttons.
