### ISSUE TITLE
Linking Extra-Life to Widget

### ISSUE THREAD

**Issue by GPREAPER** [TNotifier/Issues#14]
Hey I was just curious as to how to link my Extra-Life to the actual widget itself now that I've been able to create one? I've set my Extra-Life particpant ID to my account so that's all done, I'm just curious on how to link it to the widget.

**Comment by Oyed** [comment]
Tick "Donations" when editing your Widget.

**Comment by GPREAPER** [comment]
Oh that's it? Lol I literally did that just because. I mean I have donations for myself but that makes sense since my streamtip isn't linked to TNotifier

**Comment by Oyed** [comment]
Yeah, we have plans to allow multiple "donation" methods to be used at once after TNotifier 3 is released, at which point it'll have "Streamtip", "Extra-Life" etc. as options in Widgets instead of "Donations".
