### ISSUE TITLE
Widget Text won't show up

### ISSUE THREAD

**Issue by meowingpineapple** [TNotifier/Issues#18]
I've set up a widget for donations but the text doesn't seem to want to show. When I first did it and tested it, it was working great. The animations still work but the text won't show up. I've doubled checked my text colours, even tried creating a new widget. Can't figure out what the problem is.

**Comment by Oyed** [comment]
Could you please give me the ID of the Widget? It's the last bit of the URL when you Edit your Widget (Alternatively just paste in the URL of the Edit Widget Page and I'll get it).

Thanks!

**Comment by meowingpineapple** [comment]
https://beta.tnotifier.net/api/widget/oLFayHw0pKhH6EEvf3z4rgeB4GtfYWpmWfyPpA5JYO3zYBhHAlLNauspG9rswfYH

I thought of something this morning, could it be because my stream was not live? The text was working when the stream was live(I was trying to figure everything out). Then I believe it stopped working after I went offline and was editing the widget. I'm going off memory now so I'm not 100% sure if that timeline is correct or not.

**Comment by Oyed** [comment]
So is testing the Widget currently working? It sounds like you aren't selecting "Donations" as the Test Alert Type, and leaving it at the default "Subscribers" (Which would cause a blank alert).

**Comment by meowingpineapple** [comment]
I just tried it again making sure to double check that "donation" is selected. Getting the same problem still. Animation works but text does not.

**Comment by Oyed** [comment]
Just going to move the Widget to my account to try and reproduce this.

**Comment by Oyed** [comment]
Haha. Found the issue.
You had your text colour set to black.

I've changed it to white and put the Widget back on your Account.
Thanks!

**Comment by meowingpineapple** [comment]
Oh wow, I sat there for 30 minutes last night trying to figure it out. I feel silly now. Thanks!
