### ISSUE TITLE
Followers Issue | HITBOX

### ISSUE THREAD

**Issue by ahndar** [TNotifier/Issues#19]
Ok. I investigate this issue of followers list, and it's not the order problem. (sorry for misleading)
I figured that the list tnotifier sends thru "Tracker" is not list of my followers, It's list of some different user or i dont know. 

But list I see in dashboard "10 Latest Followers" is OK.

PS. Do you consider adding alignment to "Tracker" not only scroll but for example align left , align right, center ??

**Comment by ahndar** [comment]
I see the same issue with "Goals", number of followers used to show progres bar is taken from not my list. Number is equal to the list show in tracker.

**Comment by Oyed** [comment]
I cannot reproduce this. Are you sure you're talking about Followers? I see an issue with Subscriber trackers (It's displaying in the reverse order, Oldest -> Newest), but Follower Trackers work perfectly fine for me.

**Comment by Oyed** [comment]
I have found an issue that might cause these problems for you - please try now.

As for the Goals; was it only ever defaulting to 50 at max? If so, this is fixed now too. Regardless, please do try again and let me know if these issues persist.

**Comment by ahndar** [comment]
Ok. It didnt work. I try to make video of this and show what is going on. ^^

**Comment by ahndar** [comment]
https://youtu.be/fPtm3YIkxWw Video where i try to explain the issue.

**Comment by Oyed** [comment]
Can you please paste the API URL in here for me, and don't reset your API key after doing so.

**Comment by Oyed** [comment]
Please try again - I believe this is fixed now.

**Comment by ahndar** [comment]
All works fine.
