### ISSUE TITLE
Hitbox and Twitch Donation Tracker Not Pushed to xSplit/Stream

### ISSUE THREAD

**Issue by iBuilderLive** [TNotifier/Issues#21]
I've attached and authenticated streamtip to the beta account for both hitbox and twitch so they both share the same streamtip account (which is a twitch login).

Both the twitch and hitbox dashboards show all the related information in the dashboard, recent donations and top donations populate perfectly.

when I create a tracker to list all time donations -> Newest to Oldest -> any number of records -> %username% %currency%%amount% -> any delimiter.  with or without custom CSS, the tracker works fine as expected in the "launch" browser viewer, however does not or is not being pushed to display in xsplit, and as such does not show in live stream.    odd that it works in the browser, but not in xsplit.

cheers
iBuilderLive

**Comment by Oyed** [comment]
Which version of XSplit are you using? And what URL are you pasting in to XSplit?

**Comment by iBuilderLive** [comment]
xSplit broadcaster ver 2.5.1509.0820

this is the link from the tracker on hitbox
https://beta.tnotifier.net/api/tracker/oZqx0I5FHm7mW12LAzTLw6xgKeY1P8ZXzDYnWmHdA5aNpzD8HlERiqV9PyQIJMVu

this is the link the browser "launcher" for hitbox 
https://beta.tnotifier.net/tracker/use/26113

this is the link from the tracker on twitch
https://beta.tnotifier.net/api/tracker/i7wErZpWcKJz9mzHmXdyyDFxV3d9kZCZ36L7WcNlOJicdijlZgId38idk1FMcNDl

this is the link for the browser "Launch" from twitch
https://beta.tnotifier.net/tracker/use/26084

**Comment by Oyed** [comment]
This should be fixed now!

**Comment by iBuilderLive** [comment]
and so it is.. once again bro, you're awesome.  Thanks much!
