### ISSUE TITLE
Goal widget not showing current Extra Life donation total even with Auto-Fill enabled

### ISSUE THREAD

**Issue by willfe** [TNotifier/Issues#22]
I've linked my TNotifier account with my Extra Life participant ID successfully (my dashboard shows recent donations correctly), but when I create a Goal widget with Auto-Fill enabled, the total shown starts at $0. When I use the testing utility to send test donations to the widget, it updates the total accordingly, but I can't seem to coax existing donations into it.

Come to think of it, a workaround could be just to send a "test" donation with the desired starting amount (just in case this can't be fixed before tomorrow's event and somebody else comes across this).

**Comment by Oyed** [comment]
Hey,

Unfortunately this isn't a bug; we support multiple donation services and the Extra Life implementation was very last-minute, and as none of the other services give us the required information to auto-fill Goals, we haven't implemented it for Extra Life.

This'll be something we can add in the future, however it won't make it in before tomorrow's event.

Thanks :)
