### ISSUE TITLE
Slider Thumb Indexing

### ISSUE THREAD

**Issue by JoFont** [TNotifier/Issues#25]
Slider tool tip text is transparent and overlays with the text behind

**Comment by Oyed** [comment]
Screenshot please.

**Comment by JoFont** [comment]
https://gyazo.com/7b62c777b36665bd2b378874e1577977
https://gyazo.com/cfd971f6c8e6a3fb245b27f79bd813e1

**Comment by Oyed** [comment]
Fixed in latest revision of Alpha.
