### ISSUE TITLE
My media [Preview]

### ISSUE THREAD

**Issue by JoFont** [TNotifier/Issues#34]
Would be nice to be able to preview your files by clicking somewhere
The images in full scale, the fonts with a sample text, and preview the audio

**Comment by JoFont** [comment]
Actually i noticed you can preview by clicking on permalink although its not inside Tn and smooth

**Comment by Oyed** [comment]
Images and Sounds can be previewed by clicking the buttons to visit the raw media, not going to overcomplicate the Media system with this for 3.0.
