### ISSUE TITLE
[Widget] [Text-to-Speech] Voice Selection Does Not Populate Widget Form

### ISSUE THREAD

**Issue by iBuilderLive** [TNotifier/Issues#4]
Steps to re-create:

1) create a widget, fill it with what ever data you'd like.
2) select to enable text to speech.
3) select from the voice dropdown list English UK Femake,
4) save your widget.
5) test your widget.  Note that the voice DOES save and you hear the Female UK voice.
6) edit your widget, then save it.  WITHOUT making changes to the tts settings.
7) test your widget... this time, your voice is reverted back to the default.
8) edit your widget, this time look at the tts settings and note that the voice is what ever is on the top of the list, in my case "google deutsch"

So it appears that the voice does in fact save when you make changes to the TTS settings, but your selected/saved selection should populate as the "SELECTED" item in the form when opened for editing.

Cheers mates.

**Comment by Oyed** [comment]
This is fixed now.
