### ISSUE TITLE
[Chrome] [Edge] Goals do not add correctly, they append.

### ISSUE THREAD

**Issue by iBuilderLive** [TNotifier/Issues#40]
tested in both Chrome and MS Edge
For hitbox, created 3 goals.

Subscriber Goal
   Custom Font - 28 Days Later.ttf;  Font Size: 20
   BG Colour: #00ff00; Text Colour: #00c8ff
   Type: Subscriber; Structure: Display Text
   Enable Autofill: On; Display Text: %progress% / %goal%; Goal Amount: 250
   On Complete: Do Nothing.
   Plugin URL: http://alpha.tnotifier.net/api/goal/maWfthI4nEuwKS5LPMKbPbGT3J6C0Sj9FYbyVVm3muqV89NATNQVjjKhZ015bXet

when you view the above... rather than adding 1 subscriber while using the http://alpha.tnotifier.net/test/goal tool, selecting subscriber and amount 1, you get a result like this....

first click of send test : 1 / 250
second click of send test: 11 / 250
third click of send test: 111 / 250
and so on.

the same was true for the goals I created for Followers, as well as Donations.
http://alpha.tnotifier.net/api/goal/4HNpLyqlo0OIOOz3U5nuBpDNJCZGhaoZE7sLcPwGDsLeJd6tPq4NmzRw9E8bb11k
and
http://alpha.tnotifier.net/api/goal/j5CA4mDIl8T6Y09Sk3pZvrLpoxEeBUe3KdrTExEpYg2XyYUB3RPtsw6dtIoUTaJC
respectfully.

**Comment by Oyed** [comment]
Thanks, I'll take a look tomorrow, but it's a simple fix. :+1:

**Comment by Oyed** [comment]
Fixed in latest revision of Alpha.
