### ISSUE TITLE
Randomly logged

### ISSUE THREAD

**Issue by Baker** [TNotifier/Issues#5]
I randomly log into other people's account. 

http://FPB.im/ss/09051745.png

**Comment by Oyed** [comment]
When was the last time you clicked "Log in with Twitch"?

**Comment by Baker** [comment]
Yesterday.. 



—

**Comment by Oyed** [comment]
And yesterday were you logged in as yourself?
Has it only shown you logged in on this other account when you visited today?

**Comment by Baker** [comment]
Yes 



—

**Comment by Oyed** [comment]
Switched from file-based sessions to cookie-based, not sure why I was doing it file-based to begin with. Issue it likely related to this as it doesn't happen on the Live server, only on the new Alpha server setup.

Reply if the issue persists.
