### ISSUE TITLE
Subscriber Anniversaries Still Don't Work

### ISSUE THREAD

**Issue by truktruk** [TNotifier/Issues#5]
I just fixed up my stream for the Beta and unfortunately subscriber anniversaries still do not work. They work in the testing utility just fine, but not when it actually happens on twitch.

**Comment by Oyed** [comment]
Expected. Subscriber Anniversaries are being worked on during Beta (We had to get Beta out as soon as possible). We'll announce sometime over the next week when they're added. Thanks!
