### ISSUE TITLE
Creating a new widget - Query Exception error?

### ISSUE THREAD

**Issue by t0mmyxbl** [TNotifier/Issues#6]
So when I create a new widget, that isn't particularly different to my other widget (only the sound and the fact this one is for a donation instead of followers), I get some sort of query exception error. Here is a couple images of what I see:
https://gyazo.com/72b7e5dc9dd3774d8798cc65e0595617
https://gyazo.com/4ce0a48b74bbb20caafada3158627bb1

Those images are of sort of the main headings to the 2 errors, but there is just a bunch of text and numbering underneath them.

**Comment by Oyed** [comment]
Thanks! This has been fixed now.
