### ISSUE TITLE
Purple Tool Tip Blocked

### ISSUE THREAD

**Issue by WLWarfare** [TNotifier/Issues#6]
When you put your mouse on the purple icon under the users name on the dashboard the message that displays is cut off. Tested on 1600x900 and 1920x1080

**Comment by Oyed** [comment]
Part of the Materialize Library and not likely something I can change; however I'll investigate how it's positioned and see if I can make it stay within the browser window.

**Comment by Oyed** [comment]
Fixed - moved the Tooltip to the right instead of bottom for the Sidebar.
