### ISSUE TITLE
Sound in OBS

### ISSUE THREAD

**Issue by t0mmyxbl** [TNotifier/Issues#7]
I have my widget set up and it pops up ok, although in OBS there isn't any sound along with the widget. I tested the same thing with TNotifier v2.4 and the sound works fine.

**Comment by Oyed** [comment]
Does the sound work in-browser?

**Comment by t0mmyxbl** [comment]
yep

**Comment by Oyed** [comment]
The same sound? Only .ogg works in the CLR Plugin

**Comment by t0mmyxbl** [comment]
yep both in .ogg

**Comment by Oyed** [comment]
Can you paste the URL you're using in the CLR Plugin please?

**Comment by t0mmyxbl** [comment]
http://beta.tnotifier.net/api/widget/SryAmKSxIXkO2CBBMvjt9AhDDVzZPwBeVZraqehtZj3DgjDP3wNzytaKmdSbkB5r

**Comment by Oyed** [comment]
Should be fixed now!

**Comment by t0mmyxbl** [comment]
still dont think its working :/

**Comment by Oyed** [comment]
Did you close and re-open OBS?

**Comment by t0mmyxbl** [comment]
I did once, ill restart again and have a go

**Comment by t0mmyxbl** [comment]
still nothing

**Comment by Oyed** [comment]
Remember that you don't hear sounds from the CLR Plugin, only the stream does

**Comment by t0mmyxbl** [comment]
sure? I can hear it through the plugin with tnotifier 2.4?

**Comment by Oyed** [comment]
I believe I've found the cause - will update shortly.

**Comment by Oyed** [comment]
Can confirm this is now fixed on my end (You're right about CLR Plugin playing sound!)

Thanks, let me know if it's alright on your end :)

**Comment by t0mmyxbl** [comment]
ok thanks, ill try it and get back to you

**Comment by t0mmyxbl** [comment]
yep sorted :)

**Comment by Oyed** [comment]
Great! And thanks again for the report, I really appreciate it!
