### ISSUE TITLE
No Tool Tips When Submitting a Ticket

### ISSUE THREAD

**Issue by WLWarfare** [TNotifier/Issues#9]
When you are creating a new ticket you have the option to bold, attach image, url, etc. However most users might not know what each thing does. I would suggest adding a tool tip to each icon. 

http://puu.sh/k3KX9/6e5264262d.png

**Comment by Oyed** [comment]
The editor is a library and not something I can change; I think for the most part it's self-explanatory, otherwise, people just won't bold things, no bigee
