### ISSUE TITLE
Cannot Create Widgets for Extra-Life

### ISSUE THREAD

**Issue by GPREAPER** [TNotifier/Issues#9]
Any time I try to create a widget to be used for my extra life stream coming up, I get this:

QueryException in Connection.php line 651:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'custom_sound_anniversaries' cannot be null (SQL: insert into `widgets` (`user_id`, `name`, `api_key`, `background_colour`, `alert_background_colour`, `alert_text_colour`, `width`, `height`, `speed`, `stay`, `delay`, `font`, `font_size`, `animation_in`, `animation_out`, `track`, `custom_css`, `min_donation`, `min_host_viewers`, `subscriber_text`, `follower_text`, `donations_text`, `hosts_text`, `anniversary_text`, `sound_volume`, `sound_subscriptions`, `sound_anniversaries`, `sound_follows`, `sound_donations`, `sound_hosts`, `custom_sound_subscriptions`, `custom_sound_anniversaries`, `custom_sound_follows`, `custom_sound_donations`, `custom_sound_hosts`, `speech_enabled`, `speech_delay`, `speech_voice_uri`, `speech_voice_lang`, `speech_volume`, `cache`, `donation_chat`, `announcements`, `announcement_delay`, `updated_at`, `created_at`) values (87662, Extra-Life, KMYn8lPr9Wmwunuv2ia8IZi8jTRhpQ7EDtr3S1JAlAlgT9rqf0Q5Z4Jb4sf40xOU, #00ff00, #ffffff, #000000, 580, 110, 1.0, 3000, 0, custom::Arial, 20, fadeIn, fadeOut, 2, /**
* You can enter custom CSS here which will be applied automatically.
*
* Don't know CSS0 Try some of our pre-built designs from the CSS Library!
*/

, 0, %username% has just subscribed!, %username% has just followed!, %username% (%currency%%amount%): %comment%, , , 0.5, , chime, , , , , , , , , 0, 0, Google Deutsch, de-DE, 0.5, 0, 0, Announcement 1
Announcement 2
Announcement 3
Announcement 4, 10000, 2015-11-04 23:44:40, 2015-11-04 23:44:40, ?))

Looks like you guys need to go back to the code again and check your php. If this could be fixed before saturday that'd be great. Side note, I am trying to set it up for my Hitbox account but I imagine that it's probably happening on the Twitch side too. I did check the issues that have been closed out and honestly they probably shouldn't have been closed cause this is still an issue.

**Comment by Oyed** [comment]
This should be fixed now. Thanks!

**Comment by Oyed** [comment]
As per your edit and new closing comment on the issue, you are incorrect, the issue you reported was only affecting Hitbox users. The other issue was a similar issue, but affected Twitch users.
